#!/bin/sh

rm -rf /root/install
rm -rf /root/VpsPack
rm -rf /root/vypbA
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Atualizando" ; tput sgr0
echo ""

echo "Digite o dominio"
read -p ": " D1

echo "Digite o dominio"
read -p ": " D2

IP=$(wget -qO- ipv4.icanhazip.com)
IP1=$(host $D1 | awk '{print $NF}')

apt-get update
apt-get upgrade -y

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Instalando GIT" ; tput sgr0
echo ""

sleep 1.5s

apt-get install git -y
git clone https://github.com/jluanb/VpsPack.git
clear
cd VpsPack
rm -rf README.md
rm -rf install
for arqs in `ls`
do
rm /bin/$arqs 2>/dev/null
mv $arqs /bin
chmod +x /bin/$arqs
done

clear

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Instalando Squid3" ; tput sgr0

sleep 2s

apt-get install squid3 -y 1> /dev/null 2> /dev/null
apt-get install ufw -y 1> /dev/null 2> /dev/null
 
echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
echo "Port 443" >> /etc/ssh/sshd_config
echo "Port 2510" >> /etc/ssh/sshd_config
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo "PermitTunnel yes" >> /etc/ssh/sshd_config
echo "UseDns no" >> /etc/ssh/sshd_config
echo "Banner /etc/banner.txt" >> /etc/ssh/sshd_config

service ssh restart 1> /dev/null 2> /dev/null
service sshd restart 1> /dev/null 2> /dev/null
/etc/init.d/sshd restart
/etc/init.d/ssh restart

cd /etc/squid*
echo "http_port 80" > squid.conf
echo "http_port 8080" >> squid.conf
echo "http_port 8799" >> squid.conf
echo "http_port 3128" >> squid.conf
echo "http_port 1080" >> squid.conf
echo "visible_hostname luan-ssh" >> squid.conf
echo "acl ip dstdomain -i $IP" >> squid.conf
echo "acl ip dstdomain -i $IP1" >> squid.conf
echo "acl ip dstdomain -i $D1" >> squid.conf
echo "acl ip dstdomain -i $D2" >> squid.conf
echo "acl luan dstdomain -i 127.0.0.1" >> squid.conf
echo "acl luan dstdomain -i 200.169.126.11" >> squid.conf
echo "acl luan dstdomain -i .claro.com.br" >> squid.conf
echo "acl luan dstdomain -i .claro.com" >> squid.conf
echo "acl luan dstdomain -i .vivo.com.br" >> squid.conf
echo "acl luan dstdomain -i .oi.com.br" >> squid.conf
echo "acl luan dstdomain -i .clarosomdechamada.com.br" >> squid.conf
echo "acl luan dstdomain -i .bradescocelular.com.br" >> squid.conf
echo "acl luan dstdomain -i .tim.com.br" >> squid.conf
echo "acl luan dstdomain -i .wcad.com" >> squid.conf
echo "acl luan dstdomain -i .ddivulga.com" >> squid.conf
echo "acl luan dstdomain -i localhost" >> squid.conf
echo "acl luan dstdomain -i localnet" >> squid.conf
echo "acl accept dstdomain -i GET" >> squid.conf
echo "acl accept dstdomain -i POST" >> squid.conf
echo "acl accept dstdomain -i OPTIONS" >> squid.conf
echo "acl accept dstdomain -i CONNECT" >> squid.conf
echo "acl accept dstdomain -i PUT" >> squid.conf
echo "acl HEAD dstdomain -i HEAD" >> squid.conf
echo "acl accept dstdomain -i TRACE" >> squid.conf
echo "acl accept dstdomain -i OPTIONS" >> squid.conf
echo "acl accept dstdomain -i PATCH" >> squid.conf
echo "acl accept dstdomain -i PROPATCH" >> squid.conf
echo "acl accept dstdomain -i DELETE" >> squid.conf
echo "acl accept dstdomain -i REQUEST" >> squid.conf
echo "acl accept dstdomain -i METHOD" >> squid.conf
echo "acl accept dstdomain -i NETDATA" >> squid.conf
echo "acl accept dstdomain -i MOVE" >> squid.conf
echo 'acl accept dstdomain -i "/etc/squid3/payload.txt"' >> squid.conf
echo "acl all src 0.0.0.0/0" >> squid.conf
echo "http_access allow ip" >> squid.conf
echo "http_access allow luan" >> squid.conf
echo "http_access allow accept" >> squid.conf
echo "http_access allow HEAD" >> squid.conf
echo "http_access deny all" >> squid.conf
echo "forwarded_for off" >> squid.conf
echo "request_header_access Allow allow all" >> squid.conf
echo "request_header_access Authorization allow all" >> squid.conf
echo "request_header_access WWW-Authenticate allow all" >> squid.conf
echo "request_header_access Proxy-Authorization allow all" >> squid.conf
echo "request_header_access X-Online-Host allow all" >> squid.conf
echo "request_header_access Proxy-Authenticate allow all" >> squid.conf
echo "request_header_access Cache-Control allow all" >> squid.conf
echo "request_header_access Content-Encoding allow all" >> squid.conf
echo "request_header_access Content-Length allow all" >> squid.conf
echo "request_header_access Content-Type allow all" >> squid.conf
echo "request_header_access Date allow all" >> squid.conf
echo "request_header_access Expires allow all" >> squid.conf
echo "request_header_access Host allow all" >> squid.conf
echo "request_header_access If-Modified-Since allow all" >> squid.conf
echo "request_header_access Last-Modified allow all" >> squid.conf
echo "request_header_access Location allow all" >> squid.conf
echo "request_header_access Pragma allow all" >> squid.conf
echo "request_header_access Accept allow all" >> squid.conf
echo "request_header_access Accept-Charset allow all" >> squid.conf
echo "request_header_access Accept-Encoding allow all" >> squid.conf
echo "request_header_access Accept-Language allow all" >> squid.conf
echo "request_header_access Content-Language allow all" >> squid.conf
echo "request_header_access Mime-Version allow all" >> squid.conf
echo "request_header_access Retry-After allow all" >> squid.conf
echo "request_header_access Title allow all" >> squid.conf
echo "request_header_access Connection allow all" >> squid.conf
echo "request_header_access Proxy-Connection allow all" >> squid.conf
echo "request_header_access User-Agent allow all" >> squid.conf
echo "request_header_access Cookie allow all" >> squid.conf
echo "request_header_access Referer allow all" >> squid.conf
echo "request_header_access Host allow all" >> squid.conf
echo "via off" >> squid.conf
 
service squid3 restart 1> /dev/null 2> /dev/null
/etc/init.d/squid* restart 1> /dev/null 2> /dev/null
 
ufw allow 443 1>/dev/null 2>/dev/null
ufw allow 80 1>/dev/null 2>/dev/null
ufw allow 8080 1>/dev/null 2>/dev/null
ufw allow 8799 1>/dev/null 2>/dev/null
ufw allow 3128 1>/dev/null 2>/dev/null
ufw allow 1080 1>/dev/null 2>/dev/null

echo ".claro.com.br
.claro.com
.claroideas.com
.claroideias.com.br
.claromusica.com
.clarosomdechamada.com.br
.clarovideo.com
.netclaro.com.br
.oi.com.br
.speedtest.net
.tim.com.br
.timanamaria.com.br
.vivo.com.br
.bradescocelular.com.br
v.whatsapp.com
loja.oi.com.br
.rdio.com/rewrite.pandora.com
.vivoblog.com.br
.sascdn.com
.nethoes.com.br
.vivomms.com.br
.cloudfront.net
.ddivulga.com
.site2unblock.com
google.com
.starwarsclub.co
.clarobr.mobi
.operamini.com
.mobicare.com.br/api/android-v1/1/home
.oi.com.br/gratis
integradorproxy.bizvox.com.br:443
.serving-sys.com
.engenharia.claro.com.br/woa/rest/SegurancaExternaSSO/v1/sso/rede/telefonia/codigo/gerar?_=1506635995265
.terra.com.br" > /etc/squid3/payload.txt 

echo "Digite a msg do Banner"
read -p ": " banner
echo "$banner" > /etc/banner.txt

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Otimizando Sysctl" ; tput sgr0
echo ""

sleep 2s

echo "#kernel.printk = 3 4 1 3
#net.ipv4.conf.all.log_martians = 1
#net.ipv4.conf.all.secure_redirects = 1
#net.ipv4.conf.all.send_redirects = 0
#net.ipv4.conf.all.accept_redirects = 0
#net.ipv6.conf.all.accept_redirects = 0
#net.ipv4.conf.all.accept_source_route = 0
#net.ipv6.conf.all.accept_source_route = 0
#net.ipv6.conf.all.forwarding=1
#net.ipv4.conf.default.rp_filter=1
#net.ipv4.conf.all.rp_filter=1
net.ipv4.ip_forward=1
fs.file-max=51200
net.core.rmem_max=67108864
net.core.wmem_max=67108864
net.core.netdev_max_backlog=250000
net.core.somaxconn=4096
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_tw_recycle=1
net.ipv4.tcp_fin_timeout=30
net.ipv4.tcp_keepalive_time=1200
net.ipv4.ip_local_port_range=10000 65000
net.ipv4.tcp_max_syn_backlog=8192
net.ipv4.tcp_max_tw_buckets=5000
net.ipv4.tcp_fastopen=3
net.ipv4.tcp_mem=25600 51200 102400
net.core.rmem_max=67108864
net.core.wmem_max=67108864
net.ipv4.tcp_rmem=4096 87380 67108864
net.ipv4.tcp_wmem=4096 65536 67108864
net.core.netdev_max_backlog=250000
net.ipv4.tcp_mtu_probing=1
net.ipv4.tcp_congestion_control=westwood" > /etc/sysctl.conf
sysctl -p
echo "westwood" > /proc/sys/net/ipv4/tcp_congestion_control

echo -e "\033[1;32mAtivando Dropbear\033[0m"

apt-get install dropbear -y 2>/dev/null
echo "NO_START=0
DROPBEAR_PORT=81" > /etc/default/dropbear

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Instalando Vnstat, Pktstat, Ntop, Nethogs e dependencias" ; tput sgr0
echo ""

sleep 1.5s

	apt-get install vnstat -y
	apt-get install pktstat -y
	apt-get install ntop graphviz -y
	apt-get install make g++ -y
	apt-get install libncurses5-dev -y
	apt-get install libpcap-dev -y
	apt-get install mitmproxy -y
	apt-get install nmap -y
	apt-get install hping3 -y
	apt-get install nload -y

	# Baixe o código fonte, compile e instale:
	wget http://github.com/raboof/nethogs/archive/v0.8.5.tar.gz
	tar xf v0.8.5.tar.gz
	cd ./nethogs-0.8.5/
	make && make install
	exit
rm -rf /root/install
rm -rf /root/VpsPack
rm -rf /root/vypbA
fi

vpspack
